### ISSUE TITLE
Folders configuration uses the project as the root instead of the worker folder

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware-labs/wasm-workers-server#116]
### Describe the bug

With #53, you can mount folders in your workers. This is useful to mount certain libraries or any arbitrary file that it's required. The configuration is done in the workers config file:

```toml
version = "1"

[[folders]]
from = "./_assets"
to = "/src/assets"
```

The `./` notation in the `from` field is confusing as it seems to refer to the current location. However, it refers to the project root folder. We should use the worker location to calculate those paths instead of the root folder.

### Reproduction steps

1. Create a new folder and `cd`
2. Add a new `_assets` folder and create an `index.html` inside with a sample content
3. Create a `worker` folder and an `index.py` file inside with the following content:

  ```py
  # Read a mounted file and return it
  def worker(request):
      s = ""
      with open("/src/assets/index.html") as f:
          s = f.read()

      return Response(s)
  ```
5. Create `worker/index.toml` file with this content:

  ```toml
  version = "1"

  [[folders]]
  from = "../_assets"
  to = "/src/assets"
  ```
6. Run `wws runtimes install python latest`
7. Run `wws .`
8. Access <http://localhost:8080/worker> and see the error
...

### Expected behavior

The `_assets` folder is properly located and mounted.
