### ISSUE TITLE
Define a common policy for dependency versions

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware-labs/wasm-workers-server#28]
Currently, we're pinning dependecy versions in different ways:

```toml
[dependencies]
wasmtime = "2.0.0"
wasmtime-wasi = "2.0.0"
anyhow = "1.0.66"
wasi-common = "2.0.0"
actix-web = "4"
env_logger = "0.9.0"
...
```

Some of them are pin to a patch while others pin to the major version. We should establish a common policy so the `cargo update` command behaves the same for all dependencies.

cc @ereslibre
