### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware-labs/wasm-workers-server#34]
Environment variables will be configured in `TOML` files. Every worker will define its own set of environment variable, which will be accessible only for them. 

As a tentative API, we will include a new `.env` resource in the TOML config file:

```
name = "test"
version = "1"

[env]
MY_ENV_VAR = "Testing!"
```

Then, the environment variables will be passed to the inner modules via WASI. The environment variables will be accessible via default env methods from the different languages.

**Comment by Angelmmiguel** [comment]
We will be able to inject environments variables by using setting the variable value to `$XXX`:

```toml
name = "test"
version = "1"

[env]
TOKEN = "$TOKEN"
MY_ENV_VAR = "VALUE"
```

In the future, we may add a more complete definition of variables. However, for now we will go with a single section to keep it simple.

```toml
name = "test"
version = "1"

[env]
MY_ENV_VAR = "VALUE"

[env.from]
environment = ["TOKEN"]
dotenv = ".env"
```
