### ISSUE TITLE
Add support for mounting folders in Wasm modules

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware-labs/wasm-workers-server#53]
Allow developers to mount folders in their Wasm workers. For that, we can use the available WASI features about filesystem. In Rust, this behavior is easy to implement as it will natively use the WASI library to interact with the filesystem. 

This feature is useful for many different use cases as we may want to inject libraries or any other arbitrary file.

# Design

By default, `wws` will ignore any file / folder that starts with `_`. This will prevent miss-configuration issues in which `wws` identifies files that are supposed to be mounted as workers.

Then, developers will configure the mounted folder as part of the worker configuration. This approach provides flexibility on:

- Folders to mount in an specific worker
- Mount point

The format of the worker configuration file will be:

```toml
name = "counter"
version = "1"

[[folders]]
  from = "_lib" 
  to = "/src/lib"
[[folders]]
  from = "_assets"
  to = "/src/assets"
```

# JavaScript

For JavaScript, the current runtime we use (QuickJS) doesn't include any library for `fs`. Even we mount the folder inside, the JavaScript code won't be able to access it. This will require to research and discuss the best approach to bring these features to javascript workers. We will do it as a separate task.
